# General parameters
GENERAL:
  MODE: 'test' # train|test|inference
  OUTPUT_PATH: '../output_test'
  EPOCHS: 2000
  START_EPOCH: 0
  LOG_INTERVAL: 100
  CUDA_DEVICE: 0 #'cuda0'
  BATCH_SIZE: 4
  NUM_WORKERS: 1
  SNAPSHOT_INTERVAL: 5
  SAVE_FEATURES: True
  TOPK: [1]
  STEP: [1]
  EVAL_INTERVAL: 1
  TERMINAL_LOG: True

# Model parameters
MODEL:
  TYPE: 'vs_gcnn'
# TYPE: 'vsgcnn_transformer'
  NUM_CLASSES:  4
  NUM_GROUPS: 4
  IN_CHANNELS: 3
  DROPOUT: 0.2
  OPTIMIZER:
    TYPE: 'adam'
    LR: 0.009
    WEIGHT_DECAY: 0.00001
  LOSS: 'cross_entropy'
  TARGETS: ['emotion_classes', 'groups']
  LAYER_CHANNELS: [32, 64, 16]
  PRETRAIN_PATH: '/home/ji/proxemo/emotion_classification/trained_models' # '/home/bala/bala/proxemo/emotion_classification/sample_data'
  PRETRAIN_NAME: 'mdl_epoch134_acc86.92_model.pth.tar'

# Data params
DATA:
  TYPE: 'multi_view'
  NUM_CLASSES:  4
  NUM_GROUPS: 4
  COORDS: 3 # in channels
  JOINTS: 16
  CYCLES: 1
  FEATURES_FILE: '/home/ji/proxemo/emotion_classification/sample_data/AugData_150_cm/features_*.h5'
  LABELS_FILE: '/home/ji/proxemo/emotion_classification/sample_data/AugData_150_cm/labels_*.h5'
